# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      -
    - name: Infra
        if: "!contains(github.ref, 'dependabot')"
        run: |
        git --no-pager diff  --output=check.txt --name-only HEAD~1..HEAD infra/
        cat check.txt
        if [[ $(wc -l <check.txt) -ge 1 ]]; then
          echo Infra
        fi
        
      - name: App
        git --no-pager diff  --output=check.txt --name-only HEAD~1..HEAD app/
        cat check.txt
        if [[ $(wc -l <check.txt) -ge 1 ]]; then
          echo App
        fi
