# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check changes
        run: |
          echo "INFRA_CHANGED=$(if [[ $(git --no-pager diff --name-only HEAD~1..HEAD infra .github | wc -l) -ge 1 ]]; then echo 1; else echo 0; fi)"  >> $GITHUB_ENV
          echo "APP_CHANGED=$(if [[ $(git --no-pager diff --name-only HEAD~1..HEAD app .github | wc -l) -ge 1 ]]; then echo 1; else echo 0; fi)"  >> $GITHUB_ENV

      - name: Infra
        if: "!contains(github.ref, 'dependabot') && env.INFRA_CHANGED == 1"
        run: |
          echo "running infra step"

      - name: App
        if: "env.APP_CHANGED == 1"
        run: |
          echo $GITHUB_ENV
          echo INFRA_CHANGED
          echo APP_CHANGED
          git --no-pager diff  --output=check.txt --name-only HEAD~1..HEAD app/ .github/
          cat check.txt
          if [[ $(wc -l <check.txt) -ge 1 ]]; then
            echo App
          fi
